#!/bin/bash

FILEPATH=$1
FILENAME_W_EXTENSION=${FILEPATH##*/}
FILENAME=${FILENAME_W_EXTENSION%.*}
FILEDIR=${FILEPATH%$FILENAME_W_EXTENSION}

JARPATH=$(dirname $BASH_SOURCE)/target/latte-compiler-1.0.1-standalone.jar
DRIPPATH=$(dirname $BASH_SOURCE)/lib/drip
DRIP_SHUTDOWN=30
LIBPATH=$(dirname $BASH_SOURCE)/target/utils.o

#suppressing 'picked up java opts' message
_SILENT_JAVA_OPTIONS="$_JAVA_OPTIONS"
unset _JAVA_OPTIONS

LATC_DRIP_ENABLED=${LATC_DRIP_ENABLED:-0}

if [ -f $JARPATH ]
then
  if [ -f $FILEDIR$FILENAME ]
  then
    rm $FILEDIR$FILENAME
  fi

  if [ $LATC_DRIP_ENABLED -ne 1 ]
  then
    ENG=java
  else
    ENG=$DRIPPATH
  fi

  $ENG $_SILENT_JAVA_OPTIONS -jar $JARPATH $FILEPATH > $FILEDIR$FILENAME.s
  RETCODE=$?
  if [ $RETCODE -ne 0 ]
  then
    rm $FILEDIR$FILENAME.s
    exit $RETCODE
  else
    gcc -m32 -o $FILEDIR$FILENAME $LIBPATH $FILEDIR$FILENAME.s
  fi
else
  echo "Executable does not exist. Did you call 'make'?"
fi
