#!/bin/bash

FILEPATH=$1
FILENAME_W_EXTENSION=${FILEPATH##*/}
FILENAME=${FILENAME_W_EXTENSION%.*}
FILEDIR=${FILEPATH%$FILENAME_W_EXTENSION}

JARPATH=$(dirname $BASH_SOURCE)/target/latte-compiler-0.9-standalone.jar
LIBPATH=$(dirname $BASH_SOURCE)/target/utils.o

if [ -f $JARPATH ]
then
  java -jar $JARPATH $FILEPATH > $FILEDIR$FILENAME.s && gcc -m32 -o $FILEDIR$FILENAME $LIBPATH $FILEDIR$FILENAME.s
else
  echo "Executable does not exist. Did you call 'make'?"
fi
